// Auto-generated from BU housing CSV data
// Layout format: "RoomType Occupancy" e.g. "Traditional Double"

export const LAYOUTS_BY_BUILDING = {
  "Lavender House": ["Traditional Single", "Traditional Double"],
  "163 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Trustee Scholars House": ["Traditional Single", "Traditional Double"],
  "Sargent College House": ["Traditional Triple", "Semi-Suite Double"],
  "Music House": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "Management House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Limited Parietal House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Education House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Common Ground House": ["Traditional Single", "Traditional Double", "Semi-Suite Triple"],
  "College of General Studies House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Classics House": ["Traditional Single", "Traditional Double", "Semi-Suite Double"],
  "625 Commonwealth Avenue": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "210–212 Bay State Road": ["Traditional Single", "Traditional Double", "Semi-Suite Double"],
  "209 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Triple"],
  "208 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "206 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "204 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "203 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "202 Bay State Road": ["Traditional Single", "Traditional Double"],
  "201 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad", "Semi-Suite Double", "Semi-Suite Triple"],
  "199 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Single", "Semi-Suite Double"],
  "196 Bay State Road": ["Traditional Single", "Traditional Double", "Apartment Double"],
  "195–197 Bay State Road": ["Traditional Single", "Traditional Double"],
  "194 Bay State Road": ["Traditional Single", "Traditional Double"],
  "192 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "188–190 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "184–186 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "182 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "181 Bay State Road": ["Traditional Single", "Traditional Triple", "Semi-Suite Double", "Semi-Suite Triple"],
  "180 Bay State Road": ["Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "178 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "177 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad"],
  "175 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad", "Semi-Suite Double"],
  "172 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "167–169 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "162–164 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "159 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "153 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double", "Semi-Suite Triple"],
  "728 Commonwealth Avenue": ["Apartment Single", "Apartment Double", "Studio Single"],
  "726 Commonwealth Avenue": ["Apartment Double", "Studio Single"],
  "722 Commonwealth Avenue": ["Apartment Double", "Studio Single"],
  "714 Commonwealth Avenue": ["Apartment Single", "Apartment Double"],
  "708 Commonwealth Avenue": ["Apartment Single", "Apartment Double"],
  "627–629 Commonwealth Avenue": ["Apartment Single", "Apartment Double"],
  "214 Bay State Road": ["Apartment Double", "Studio Single"],
  "198 Bay State Road": ["Apartment Double", "Studio Single", "Studio Double"],
  "173 Bay State Road": ["Apartment Double", "Studio Double"],
  "171 Bay State Road": ["Apartment Double", "Studio Single", "Studio Double"],
  "94 Bay State Road": ["Apartment Double", "Studio Single"],
  "139 Bay State Road": ["Studio Single", "Studio Double"],
  "133 Bay State Road": ["Apartment Single", "Apartment Double", "Studio Double"],
  "115 Bay State Road": ["Apartment Double", "Studio Single", "Studio Double"],
  "112 Bay State Road": ["Apartment Double", "Studio Single", "Studio Double"],
  "110 Bay State Road": ["Apartment Double", "Studio Single", "Studio Double"],
  "126 Bay State Road": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad"],
  "90–92 Bay State Road": ["Traditional Single", "Traditional Double", "Studio Single"],
  "117 Bay State Road": ["Semi-Suite Double", "Semi-Suite Triple", "Suite Double", "Suite Triple"],
  "81–83 Bay State Road": ["Traditional Single", "Traditional Double", "Semi-Suite Double", "Suite Double"],
  "79 Bay State Road": ["Traditional Single", "Semi-Suite Single", "Semi-Suite Double", "Studio Single"],
  "531 Beacon Street": ["Traditional Single", "Traditional Triple"],
  "517–521 Beacon Street": ["Traditional Single", "Traditional Double"],
  "481–483 Commonwealth Avenue": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad", "Semi-Suite Double", "Semi-Suite Triple", "Semi-Suite Quad"],
  "135 Bay State Road": ["Traditional Quad"],
  "Riverway House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Suite Double"],
  "Pilgrim House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad"],
  "Longwood House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad", "Semi-Suite Single", "Semi-Suite Double"],
  "Campus Center & Student Residence": ["Traditional Double", "Traditional Triple", "Suite Single", "Suite Double"],
  "Peabody Hall": ["Traditional Single", "Traditional Double", "Traditional Triple", "Suite Double", "Suite Triple"],
  "Warren Towers": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad"],
  "Sleeper Hall": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "610 Beacon Street": ["Suite Single", "Suite Double"],
  "Danielsen Hall": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "575 Commonwealth Avenue": ["Traditional Single", "Traditional Triple", "Semi-Suite Double"],
  "1019 Commonwealth Avenue": ["Suite Single", "Suite Double"],
  "The Towers": ["Traditional Double"],
  "Rich Hall": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "Kilachand Hall": ["Semi-Suite Double", "Semi-Suite Triple", "Suite Double", "Suite Triple"],
  "Claflin Hall": ["Traditional Single", "Traditional Double", "Traditional Triple", "Traditional Quad", "Semi-Suite Triple"],
  "13 Buswell Street": ["Traditional Single", "Traditional Double", "Traditional Triple", "Suite Double"],
  "Engineering House": ["Traditional Single", "Semi-Suite Double"],
  "Earth House": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "Core Curriculum House": ["Traditional Single", "Traditional Double", "Semi-Suite Double"],
  "Community Service House": ["Traditional Single", "Traditional Double", "Suite Double"],
  "522 Park Drive": ["Suite Single", "Suite Double"],
  "520 Park Drive": ["Suite Single", "Suite Double"],
  "518 Park Drive": ["Suite Single", "Suite Double"],
  "516 Park Drive": ["Suite Single", "Suite Double"],
  "514 Park Drive": ["Suite Single", "Suite Double"],
  "48 Buswell Street": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "47 Buswell Street": ["Traditional Single", "Traditional Double"],
  "45 Buswell Street": ["Traditional Single", "Traditional Double"],
  "44 Buswell Street": ["Traditional Single", "Traditional Double"],
  "43 Buswell Street": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "42 Buswell Street": ["Traditional Single", "Traditional Double"],
  "37–39 Carlton Street": ["Traditional Single", "Traditional Double", "Traditional Triple"],
  "40 Buswell Street": ["Traditional Double", "Traditional Triple", "Semi-Suite Quad"],
  "37 Buswell Street": ["Traditional Single", "Traditional Double"],
  "33 Buswell Street": ["Traditional Single", "Traditional Double", "Traditional Triple", "Suite Double"],
  "29 Buswell Street": ["Traditional Single", "Traditional Double"],
  "1053 Beacon Street": ["Traditional Single"],
  "11 Buswell Street": ["Traditional Single", "Traditional Double", "Traditional Triple", "Semi-Suite Double"],
  "17 Buswell Street": ["Apartment Single", "Apartment Double", "Studio Double"],
  "98 Mountfort Street": ["Apartment Double"],
  "96 Mountfort Street": ["Apartment Single", "Apartment Double"],
  "872 Beacon Street": ["Apartment Single", "Apartment Double", "Studio Single"],
  "870 Beacon Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "866 Beacon Street": ["Traditional Single", "Traditional Double", "Apartment Single", "Apartment Double", "Studio Single", "Studio Double"],
  "864 Beacon Street": ["Apartment Single", "Apartment Double", "Studio Single", "Studio Double"],
  "862 Beacon Street": ["Apartment Double", "Studio Single"],
  "860 Beacon Street": ["Apartment Single", "Apartment Double", "Apartment Triple", "Studio Double"],
  "856 Beacon Street": ["Apartment Double", "Studio Double"],
  "852 Beacon Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "848 Beacon Street": ["Apartment Single", "Apartment Double", "Apartment Triple", "Studio Single"],
  "844 Beacon Street": ["Apartment Single", "Apartment Double"],
  "836 Beacon Street": ["Apartment Single", "Apartment Double", "Studio Single"],
  "834 Beacon Street": ["Apartment Double", "Studio Single"],
  "832 Beacon Street": ["Apartment Double", "Studio Single"],
  "830 Beacon Street": ["Apartment Double", "Studio Double"],
  "828 Beacon Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "826 Beacon Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "824 Beacon Street": ["Studio Single", "Studio Double"],
  "820 Beacon Street": ["Apartment Single", "Apartment Double", "Studio Single", "Studio Double"],
  "74 St. Mary's Street": ["Apartment Single"],
  "6 Buswell Street": ["Apartment Single", "Apartment Double"],
  "55 Buswell Street": ["Apartment Single", "Apartment Double"],
  "52 Buswell Street": ["Apartment Single", "Apartment Double"],
  "515 Park Drive": ["Apartment Single", "Apartment Double"],
  "504 Park Drive": ["Apartment Single"],
  "500 Park Drive": ["Apartment Single", "Studio Single"],
  "50 Buswell Street": ["Apartment Single", "Apartment Double"],
  "5 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "46 Mountfort Street": ["Apartment Single", "Apartment Double"],
  "41 Buswell Street": ["Apartment Single", "Apartment Double", "Studio Single"],
  "39 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "38 Buswell Street": ["Apartment Single", "Apartment Double"],
  "35 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "34 Buswell Street": ["Apartment Double", "Studio Single"],
  "3 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double", "Studio Triple"],
  "24 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "22 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "2 Buswell Street": ["Apartment Double"],
  "1A Buswell Street": ["Apartment Single", "Apartment Double", "Studio Single"],
  "16 Arundel Street": ["Apartment Single", "Apartment Double"],
  "15 Buswell Street": ["Apartment Double", "Studio Single", "Studio Double"],
  "100 Mountfort Street": ["Apartment Single"],
  "509 Park Drive": ["Apartment Single", "Apartment Double", "Studio Single"],
  "StuVi I": ["Suite Single", "Suite Double", "Apartment Single"],
  "StuVi II": ["Apartment Single"],
};

// Buildings grouped by campus area, for <optgroup> rendering
export const BUILDINGS_BY_GROUP = {
  "Large Traditional-Style Residences": ["Warren Towers", "Claflin Hall", "Rich Hall", "Sleeper Hall", "The Towers", "Danielsen Hall", "Kilachand Hall", "610 Beacon Street", "1019 Commonwealth Avenue", "575 Commonwealth Avenue"],
  "Student Village": ["StuVi I", "StuVi II"],
  "Fenway Campus": ["Riverway House", "Pilgrim House", "Longwood House", "Campus Center & Student Residence", "Peabody Hall"],
  "Central Campus Traditional Brownstones": ["Lavender House", "163 Bay State Road", "Trustee Scholars House", "Sargent College House", "Music House", "Management House", "Limited Parietal House", "Education House", "Common Ground House", "College of General Studies House", "Classics House", "625 Commonwealth Avenue", "210–212 Bay State Road", "209 Bay State Road", "208 Bay State Road", "206 Bay State Road", "204 Bay State Road", "203 Bay State Road", "202 Bay State Road", "201 Bay State Road", "199 Bay State Road", "196 Bay State Road", "195–197 Bay State Road", "194 Bay State Road", "192 Bay State Road", "188–190 Bay State Road", "184–186 Bay State Road", "182 Bay State Road", "181 Bay State Road", "180 Bay State Road", "178 Bay State Road", "177 Bay State Road", "175 Bay State Road", "172 Bay State Road", "167–169 Bay State Road", "162–164 Bay State Road", "159 Bay State Road", "153 Bay State Road"],
  "Central Campus Apartments": ["728 Commonwealth Avenue", "726 Commonwealth Avenue", "722 Commonwealth Avenue", "714 Commonwealth Avenue", "708 Commonwealth Avenue", "627–629 Commonwealth Avenue", "214 Bay State Road", "198 Bay State Road", "173 Bay State Road", "171 Bay State Road"],
  "East Campus Traditional Brownstones": ["126 Bay State Road", "90–92 Bay State Road", "117 Bay State Road", "81–83 Bay State Road", "79 Bay State Road", "531 Beacon Street", "517–521 Beacon Street", "481–483 Commonwealth Avenue", "135 Bay State Road"],
  "East Campus Apartments": ["94 Bay State Road", "139 Bay State Road", "133 Bay State Road", "115 Bay State Road", "112 Bay State Road", "110 Bay State Road"],
  "South Campus Traditional Brownstones": ["13 Buswell Street", "Engineering House", "Earth House", "Core Curriculum House", "Community Service House", "522 Park Drive", "520 Park Drive", "518 Park Drive", "516 Park Drive", "514 Park Drive", "48 Buswell Street", "47 Buswell Street", "45 Buswell Street", "44 Buswell Street", "43 Buswell Street", "42 Buswell Street", "37–39 Carlton Street", "40 Buswell Street", "37 Buswell Street", "33 Buswell Street", "29 Buswell Street", "1053 Beacon Street", "11 Buswell Street"],
  "South Campus Apartments": ["17 Buswell Street", "98 Mountfort Street", "96 Mountfort Street", "872 Beacon Street", "870 Beacon Street", "866 Beacon Street", "864 Beacon Street", "862 Beacon Street", "860 Beacon Street", "856 Beacon Street", "852 Beacon Street", "848 Beacon Street", "844 Beacon Street", "836 Beacon Street", "834 Beacon Street", "832 Beacon Street", "830 Beacon Street", "828 Beacon Street", "826 Beacon Street", "824 Beacon Street", "820 Beacon Street", "74 St. Mary's Street", "6 Buswell Street", "55 Buswell Street", "52 Buswell Street", "515 Park Drive", "504 Park Drive", "500 Park Drive", "50 Buswell Street", "5 Buswell Street", "46 Mountfort Street", "41 Buswell Street", "39 Buswell Street", "38 Buswell Street", "35 Buswell Street", "34 Buswell Street", "3 Buswell Street", "24 Buswell Street", "22 Buswell Street", "2 Buswell Street", "1A Buswell Street", "16 Arundel Street", "15 Buswell Street", "100 Mountfort Street", "509 Park Drive"],
};

// All unique room types and occupancies (for browse filters)
export const ROOM_TYPES = ["Traditional", "Semi-Suite", "Suite", "Apartment", "Studio"];
export const OCCUPANCIES = ["Single", "Double", "Triple", "Quad"];

/**
 * Split a layout string like "Traditional Double" into its parts.
 * roomType = "Traditional", occupancy = "Double"
 */
export function parseLayout(layout) {
  if (!layout) return { roomType: "", occupancy: "" };
  const words = layout.trim().split(" ");
  return {
    occupancy: words[words.length - 1],
    roomType: words.slice(0, -1).join(" "),
  };
}

export function getLayoutsForBuilding(building) {
  return LAYOUTS_BY_BUILDING[building] || [];
}

export function getAllBuildings() {
  return Object.keys(LAYOUTS_BY_BUILDING);
}
